/**
 * ♾️ PROTOCOL OMEGA: EDGELOOP INTELLIGENCE
 * 2035 Surveillance HUD - Live NFL Market Fracture Detection
 */

"use client";

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

// ------------------------------------------------------------------
// TACTICAL COMPONENTS (The Visual Arsenal)
// ------------------------------------------------------------------

// ⚡ FRACTURE BADGE (Arbitrage)
const FractureBadge = () => (
  <motion.div
    initial={{ opacity: 0, scale: 0.8 }}
    animate={{ opacity: 1, scale: 1 }}
    className="absolute -top-3 right-6 z-30 flex items-center gap-2 bg-[#FF4D00]/10 border border-[#FF4D00] px-3 py-1 rounded-sm animate-pulse shadow-[0_0_15px_rgba(255,77,0,0.4)]"
  >
    <div className="w-1.5 h-1.5 bg-[#FF4D00] rounded-full" />
    <span className="text-[#FF4D00] text-[9px] font-mono font-bold tracking-widest uppercase">
      MARKET FRACTURE DETECTED
    </span>
  </motion.div>
);

// 📉 ALPHA SCOPE (The Edge Visualizer)
const AlphaScope = ({ market, model, color }: { market: number; model: number; color: string }) => {
  const delta = model - market;
  const isPositive = delta > 0;
  
  return (
    <div className="relative h-16 w-full bg-[#080808] border border-[#2C2F33] rounded overflow-hidden mt-4 group">
      {/* Grid Mesh */}
      <div 
        className="absolute inset-0 opacity-10" 
        style={{ 
          backgroundImage: 'linear-gradient(to right, #2C2F33 1px, transparent 1px)', 
          backgroundSize: '10px 100%' 
        }} 
      />
      
      <div className="absolute inset-0 flex items-center px-4">
        {/* Market Baseline (Grey) */}
        <div className="w-full h-0.5 bg-[#3F4145] relative z-10">
          <div className="absolute -top-3 text-[8px] text-[#3F4145] font-mono tracking-widest">
            CONSENSUS ({market.toFixed(1)}%)
          </div>
        </div>
        
        {/* Model Signal (Cyan) */}
        <motion.div 
          initial={{ width: 0 }}
          animate={{ width: `${model}%` }}
          transition={{ duration: 1, ease: "easeOut" }}
          className="absolute h-0.5 bg-[#00F5FF] z-20 shadow-[0_0_10px_#00F5FF]"
          style={{ top: '50%' }}
        >
          <div className="absolute -top-3 right-0 text-[8px] text-[#00F5FF] font-mono font-bold tracking-widest">
            MODEL ({model.toFixed(1)}%)
          </div>
        </motion.div>

        {/* The Edge Fill (Toxic Pattern) */}
        {isPositive && (
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${delta}%` }}
            transition={{ duration: 1, delay: 0.3 }}
            className="absolute h-8 border-l border-r border-[#FF4D00] opacity-80 z-10"
            style={{ 
              left: `${market}%`, 
              top: '50%',
              transform: 'translateY(-50%)',
              backgroundImage: 'repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(255, 77, 0, 0.5) 2px, rgba(255, 77, 0, 0.5) 4px)'
            }}
          />
        )}
      </div>
    </div>
  );
};

// ------------------------------------------------------------------
// MAIN DASHBOARD
// ------------------------------------------------------------------
export default function EdgeloopIntelligence() {
  const [games, setGames] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [lastUpdate, setLastUpdate] = useState<string>('');

  useEffect(() => {
    const fetchTelemetry = () => {
      // Read the file generated by the Python Miner
      fetch('/telemetry.json?' + Date.now())
        .then(res => {
          if (!res.ok) throw new Error('Telemetry offline');
          return res.json();
        })
        .then(data => {
          setGames(data.games || data || []);
          setLastUpdate(data.updated_at || new Date().toISOString());
          setLoading(false);
        })
        .catch(err => {
          console.error("Telemetry Offline:", err);
          setLoading(false);
        });
    };

    // Initial fetch
    fetchTelemetry();

    // Auto-refresh every 30 seconds
    const interval = setInterval(fetchTelemetry, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-[#050505] text-[#F0F0F0] font-mono relative overflow-hidden selection:bg-[#FF4D00] selection:text-black">
      
      {/* 📺 DIEGETIC VISOR FX (The Atmosphere) */}
      <div className="fixed inset-0 pointer-events-none z-50 opacity-10 mix-blend-overlay bg-[url('https://grainy-gradients.vercel.app/noise.svg')]"></div>
      <div className="fixed inset-0 pointer-events-none z-40 bg-gradient-to-b from-black/20 via-transparent to-black/80" />
      
      {/* Micro-labels */}
      <div className="absolute top-4 left-4 text-[8px] text-[#2C2F33] font-mono uppercase tracking-widest z-50">
        R_SYS_01
      </div>
      <div className="absolute top-4 right-4 text-[8px] text-[#2C2F33] font-mono uppercase tracking-widest z-50">
        LIVE_FEED
      </div>
      
      <div className="relative z-10 max-w-7xl mx-auto p-6">
        
        {/* HEADER */}
        <header className="mb-16 border-b border-[#2C2F33] pb-6 flex justify-between items-end">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="w-2 h-2 bg-[#00F5FF] animate-pulse rounded-full shadow-[0_0_10px_#00F5FF]"></span>
              <span className="text-[#00F5FF] text-[10px] tracking-[0.3em] font-bold">
                PROTOCOL OMEGA // LIVE NFL FEED
              </span>
            </div>
            <h1 className="text-6xl font-bold tracking-tighter text-white">
              EDGELOOP <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#00F5FF] to-[#00a3aa]">INTELLIGENCE</span>
            </h1>
            {lastUpdate && (
              <div className="text-[#3F4145] text-[9px] mt-2 font-mono">
                Last Update: {new Date(lastUpdate).toLocaleTimeString()}
              </div>
            )}
          </div>
          <div className="text-right hidden md:block">
            <div className="text-[#3F4145] text-[10px] uppercase tracking-widest mb-1">Targets Active</div>
            <div className="text-[#00FF94] text-xl font-bold tabular-nums">{games.length}</div>
          </div>
        </header>

        {/* THEATER OF OPERATIONS */}
        {loading ? (
          <div className="text-[#00F5FF] animate-pulse text-center py-20">
            <div className="text-lg mb-2">AWAITING SATELLITE UPLINK...</div>
            <div className="text-sm text-[#3F4145]">Run: python miner.py</div>
          </div>
        ) : games.length === 0 ? (
          <div className="text-[#00F5FF] animate-pulse text-center py-20">
            <div className="text-lg mb-2">NO TARGETS DETECTED</div>
            <div className="text-sm text-[#3F4145]">Run: python miner.py to initialize data feed</div>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {games.map((game) => {
              const hasEdge = game.model.edge > 5;
              
              return (
                <motion.div
                  key={game.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  className={`group relative bg-[#1A1D21]/40 backdrop-blur-md border ${
                    hasEdge ? 'border-[#FF4D00]' : 'border-[#2C2F33]'
                  } p-6 transition-all duration-500 hover:bg-[#1A1D21]/60 hover:border-[#00F5FF]/50`}
                >
                  
                  {game.model.is_fracture && <FractureBadge />}

                  {/* GAME HEADER */}
                  <div className="flex justify-between items-start mb-6">
                    <div>
                      <div className="text-[#3F4145] text-[9px] tracking-[0.2em] mb-2 font-bold uppercase">
                        {game.status}
                        {game.clock && ` • ${game.clock}`}
                      </div>
                      <div className="text-3xl font-bold text-white tracking-tight flex items-center gap-3">
                        <span style={{color: `#${game.away.color}`}}>{game.away.abbr}</span>
                        <span className="text-[#2C2F33] text-xl">/</span>
                        <span style={{color: `#${game.home.color}`}}>{game.home.abbr}</span>
                      </div>
                      <div className="text-sm text-[#3F4145] mt-1 font-bold">
                        {game.away.score} - {game.home.score}
                      </div>
                    </div>
                    
                    {game.model.velocity === 'CRITICAL' && (
                      <div className="flex flex-col items-end">
                        <div className="text-[#FF4D00] text-[9px] font-bold border border-[#FF4D00] px-2 py-0.5 animate-pulse">
                          ⚠ KINETIC SURGE
                        </div>
                      </div>
                    )}
                  </div>

                  {/* ALPHA SCOPE */}
                  <div className="mb-6">
                    <div className="flex justify-between text-[9px] text-[#3F4145] mb-2 uppercase tracking-widest font-bold">
                      <span>Market Variance</span>
                      <span className={hasEdge ? "text-[#00FF94]" : "text-[#3F4145]"}>
                        EDGE: +{game.model.edge}%
                      </span>
                    </div>
                    <AlphaScope 
                      market={game.market.implied_prob} 
                      model={game.model.prob} 
                      color={game.home.color} 
                    />
                  </div>

                  {/* TELEMETRY */}
                  <div className="grid grid-cols-2 gap-px bg-[#2C2F33] border border-[#2C2F33]">
                    <div className="bg-[#080808] p-4">
                      <div className="text-[#3F4145] text-[9px] mb-1 tracking-widest">CONSENSUS</div>
                      <div className="text-[#F0F0F0] text-xl font-medium tabular-nums">
                        {game.home.abbr} {game.market.spread > 0 ? '+' : ''}{game.market.spread}
                      </div>
                    </div>
                    <div className={`p-4 ${hasEdge ? 'bg-[#FF4D00]/5' : 'bg-[#080808]'}`}>
                      <div className={hasEdge ? "text-[#FF4D00] text-[9px] mb-1 font-bold" : "text-[#00F5FF] text-[9px] mb-1"}>
                        MODEL
                      </div>
                      <div className={`text-xl font-bold tabular-nums ${hasEdge ? "text-[#FF4D00]" : "text-[#00F5FF]"}`}>
                        {game.home.abbr} {game.model.spread > 0 ? '+' : ''}{game.model.spread}
                      </div>
                    </div>
                  </div>

                </motion.div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
